export default [
  {
    id: '1',
    icon: 'dashboard',
    name: 'Dashboard',
    zhName: '仪表盘',
    route: '/dashboard',
  },
  {
    id: '2',
    name: 'System',
    zhName: '系统',
    icon: 'setting',
  },
  {
    id: '21',
    breadcrumbParentId: '1',
    menuParentId: '2',
    name: 'Management user',
    zhName: '管理员',
    icon: 'user',
    route: '/adminUser',
  },
  {
    id: '22',
    breadcrumbParentId: '1',
    menuParentId: '2',
    name: 'Management group',
    zhName: '管理组',
    icon: 'team',
    route: '/adminGroup',
  },
  {
    id: '3',
    name: 'Content',
    zhName: '内容',
    icon: 'file-text',
  },
  {
    id: '31',
    breadcrumbParentId: '1',
    menuParentId: '3',
    name: 'Category',
    zhName: '分类',
    icon: 'filter',
    route: '/category',
  },
  {
    id: '32',
    breadcrumbParentId: '1',
    menuParentId: '3',
    name: 'Article',
    zhName: '文章',
    icon: 'file-text',
    route: '/article',
  },
  {
    id: '33',
    breadcrumbParentId: '32',
    menuParentId: '-1',
    name: 'Article Edit',
    zhName: '文章编辑',
    route: '/article/:_id',
  },
  {
    id: '34',
    breadcrumbParentId: '1',
    menuParentId: '3',
    name: 'Media',
    zhName: '资源',
    icon: 'cloud',
    route: '/media',
  },
  {
    id: '9',
    breadcrumbParentId: '1',
    name: 'Request',
    zhName: 'Request',
    icon: 'api',
    route: '/request',
  },
]
